# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Benjamin Hiltpolt
email: benjamin.hiltpolt@gmail.com
description: >
  (Coding) Stuff I am interested in.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hilben.github.io/" # the base hostname & protocol for your site
twitter_username: vbenni 
github_username:  hilben

# Build settings
markdown: kramdown
